import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '../components/Navbar'
import AlertBar from "@/components/AlertBar";
import Layout from "@/components/Layout";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      
      <body className={inter.className}>
        <Layout>
          <Navbar />
          <AlertBar />
          {children}
        </Layout>
          
        
      </body>
    </html>
  );
}
