import type { GetServerSideProps, Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '../components/Navbar'
import AlertBar from "@/components/AlertBar";
import { AuthProvider } from "@/contexts/authContext";
import createApolloClient from "@/lib/apolloClient";
import { ApolloProvider } from "@apollo/client";
import client from "@/lib/apolloClient";


const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 

{
  
  return (
    <html lang="en">
      
      
      <body className={inter.className}>
      <ApolloProvider client={client}>
          <AuthProvider>
            <Navbar />
            <AlertBar />
            {children}
          </AuthProvider>
        </ApolloProvider>
       
          
        
      </body>
    </html>
  );
}
